# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubegraf < Formula
  desc "Advanced Kubernetes visualization tool with terminal UI and web dashboard"
  homepage "https://kubegraf.io"
  version "1.7.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubegraf/kubegraf/releases/download/v1.7.12/kubegraf-darwin-amd64.tar.gz"
      sha256 "d374bd2f34dd04182df173f844e4f46c16ca2ee5298506b15a8e143a32f00226"

      def install
        bin.install "kubegraf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubegraf/kubegraf/releases/download/v1.7.12/kubegraf-darwin-arm64.tar.gz"
      sha256 "705e506777600952856fd8afb0ab3e0045fa9171cdf872bc207500994f889985"

      def install
        bin.install "kubegraf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubegraf/kubegraf/releases/download/v1.7.12/kubegraf-linux-amd64.tar.gz"
      sha256 "aa9a1a55689e1bf1414e60ea4d0daa027d8980d5443b1c4cda30c665e9a151db"
      def install
        bin.install "kubegraf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubegraf/kubegraf/releases/download/v1.7.12/kubegraf-linux-arm64.tar.gz"
      sha256 "3a121a0d8f6a22d79a33a4a67b296dfdf164c7bc7834d424ea3656572e49c33c"
      def install
        bin.install "kubegraf"
      end
    end
  end

  test do
    system "#{bin}/kubegraf", "--version"
  end
end
